### ISSUE TITLE
添加是否联动平滑字体的选项（或者有什么办法能让一开始就加载平滑字体）

### ISSUE THREAD

**Issue by ghost** [kappa-maintainer/ModernSplash#1]
平滑字体不会在一开始就加载，到中间的时候突然就变成平滑字体了，感觉比较难受

**Comment by kappa-maintainer** [comment]
我看看能不能加字体设置吧

**Comment by kappa-maintainer** [comment]
不好办，目前改字体只能在.minecraft下创建resources文件夹并将字体资源包解压进去
我再看看平滑字体的实现

**Comment by kappa-maintainer** [comment]
似乎是平滑字体用反射针对了启动界面，从而启动时维持原字体
但这一措施在这里失效了，因为实际的启动界面已经变了
我可以用mixin强行改掉，但还是在对面改更好
建议找平滑字体反馈
