### ISSUE TITLE
How to use custom logoTexture?

### ISSUE THREAD

**Issue by xJon** [kappa-maintainer/ModernSplash#10]
I want to use a logoTexture that has a [built-in red background](https://static.wikia.nocookie.net/logopedia/images/2/2c/Mojang_Studios.svg/revision/latest?cb=20200614092049), so the loading screen background can still be white, as well as lifting it up (vertically) a bit.
What I've tried:
- Using Resource Loader to override the existing texture (with the default path under the `modernsplash` namespace), but then it just shows the default texture the mod ships with.
- Using [Resource Loader](https://www.curseforge.com/minecraft/mc-mods/resource-loader) to set a new resource location under the same or a different namespace and target it in `splash.properties`, but it shows the whole loading screen as black and then [crashes](https://mclo.gs/qjEwaXs) - it seems to not recognize the new texture (or any new namespace).
-  
The only solution that worked was manually changing the file inside `modernsplash-1.12.2-1.2.2.2.jar`.

**Comment by kappa-maintainer** [comment]
The splash screen is at very low level and is using .minecraft/resources folder as resource pack.
Using a resource loader to do this may produce conflict, since they are using the same path

**Comment by xJon** [comment]
- Trying to use Resource Loader to override the texture in `\resources\minecraft\textures\gui\title\mojang.png` doesn't work (it just shows/prioritizes the default texture shipped with the mod)
- Trying to change the config to use `logoTexture=minecraft\:textures/gui/title/mojang.png` just shows the old (1.12.2 default) texture
- Trying to launch with a resource pack overriding either `modernsplash\textures\gui\title\mojang.png` or `minecraft\textures\gui\title\mojang.png` just shows/prioritizes the default texture shipped with the mod.

Unless I did something wrong, do you know any other way to modify the texture, or do you recommend just shipping the mod with the texture changed inside?
Another possible idea is having the [built-in red background](https://i.imgur.com/lYvoFSJ.png) as a configurable option.

**Comment by kappa-maintainer** [comment]
The default namespace is in fact ```modernsplash:textures/gui/title/mojang.png```
Just put it in ```.minecraft\resources\modernsplash\textures\gui\title\mojang.png``` should work

**Comment by xJon** [comment]
That's probably the first thing I tried and unfortunately it does not work (it shows the default texture shipped with the mod jar)

**Comment by kappa-maintainer** [comment]
Sorry but I haven't made resource packs in a while, the correct path is ```.minecraft\resources\assets\modernsplash\textures\gui\title\mojang.png```

**Comment by xJon** [comment]
Oh, right. I'm silly.
Thank you for the help.
