### ISSUE TITLE
No Mojang Logo When Light Mod

### ISSUE THREAD

**Issue by Desoroxxx** [kappa-maintainer/ModernSplash#2]
This mod is amazing but there is some problems

The mod when in Light mod does not show Mojang logo:
![image](https://user-images.githubusercontent.com/82710983/182023245-7711a2de-f34e-44fb-82e5-0b2be9642a57.png)

Also when in dark mod the Mojang is grey instead of red.

**Comment by kappa-maintainer** [comment]
Try delete the splash.properties file in config folder then restart the game

**Comment by kappa-maintainer** [comment]
You can customize colours of most elements in splash.properties too, if you want red logo in dark mode

**Comment by Desoroxxx** [comment]
Thanks, the config file was corrupt somehow by an old mod I had that had the same config name.

Anyway it works now amazing mod, can I change the Mojang Studio in the config?

**Comment by kappa-maintainer** [comment]
Yes, just change logoDark to 0xFFFFFF (white) or 0xEF323D (red)

**Comment by Desoroxxx** [comment]
Sorry I did not make a good sentence can I put my own logo instead of the Mojang Studio?

**Comment by Desoroxxx** [comment]
Also is there a like template of what a font file should look like?

**Comment by kappa-maintainer** [comment]
Both logo and font can be overridden by a resource pack extracted to .minecraft/resources/ folder
Overriding the logo should place new logo to resources/modernsplash/textures/gui/title/mojang.png
Overriding the font should use resources/minecraft/textures/font/ascii.png
You can find examlpes of ascii.png by searching for font resource packs

**Comment by Desoroxxx** [comment]
Thanks a lot!

**Comment by ferreiraalex** [comment]
Minecraft\resources\assets\modernsplash\textures\gui\title work correct if it can help you

**Comment by ferreiraalex** [comment]
![image](https://github.com/kappa-maintainer/ModernSplash/assets/10839855/ffef19b1-51c7-4162-b8aa-2e370d8ccdd6)
