### ISSUE TITLE
[1.12] Doesn't work.

### ISSUE THREAD

**Issue by MagmaSlime123** [kappa-maintainer/ModernSplash#5]
Title.

MixinBooter and ModernSplash are both present, game acts as if ModernSplash isn't installed.

Game was restarted twice, nothing changed.

![image](https://user-images.githubusercontent.com/51277766/227615012-dc8d302d-aeaf-44e8-bc7f-340a9c43cbc5.png)

![image](https://user-images.githubusercontent.com/51277766/227615294-725c1edc-cf3a-4eee-b883-aad916a7a8cf.png)

**Comment by kappa-maintainer** [comment]
I will check what is wrong here, please use 1.2.1 as a workaround

**Comment by kappa-maintainer** [comment]
1.2.2.1 should have fixed this, I mess up the Mixin config too much when dealing with Smooth Fonts

**Comment by MagmaSlime123** [comment]
Ah, thanks!
